### ISSUE TITLE
CC0 License is more appropriate than Apache

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt-fresh#10]
See https://wiki.creativecommons.org/wiki/CC0

**Comment by hseeberger** [comment]
I don't worry too much about licensing and so far Apache license has been a good friend. Do you see substantial issues with the Apache license being used for this project?

**Comment by mslinn** [comment]
Yes. 3rd parties may not alter licenses, so all projects created from your template are copyright Heiko. Investors won't allow the

**Comment by hseeberger** [comment]
Wait. sbt-fresh itself is Apache license. But the stuff it creates is not, at least not necessarily, because you can tweak it (still under my copyright and Apache license) to produce projects that have any license (take a look at `Template.scala`). The copyright owner can be set via an sbt setting anyway.

**Comment by mslinn** [comment]
By "tweak" you mean "fork", right? If so, a third party who wanted to make life difficult for your users could do so. In the US, at least, threatening legal action over dubious issues is a common form of extortion. Best if you explicitly provide a mechanism to generate projects free of all intellectual property claims, and expressly state in the fresh license that this is the intent.

**Comment by hseeberger** [comment]
Well, honestly, the main purpose of this little piece of software is to make my life easier. I have made it an OS project so others can benefit from it, if they like.

Having said that, I open for contributions. So if you have the energy to turn this into a more useful project, I'm looking forward to your PR.

Please notice that I'm willing to change the license of sbt-fresh itself, but the (default) projects that it creates have to be with Apache license.
