### ISSUE TITLE
Unresolved dependency

### ISSUE THREAD

**Issue by epot** [sbt/sbt-fresh#120]
I am trying to follow the readme but I get the following error when running sbt:

    [error] (*:update) sbt.ResolveException: unresolved dependency: de.heikoseeberger#sbt-fresh;3.1.10: not found

I cannot find where is delivered this component, I did not find it in Maven central :-/.

**Comment by hseeberger** [comment]
This looks like you added sbt-fresh to your `build.sbt`, but you have to add it to `project/plugins.sbt` or even better to `~/.sbt/0.13/plugins/plugins.sbt`.

**Comment by epot** [comment]
No, I did put it in ~/.sbt/0.13/plugins/plugins.sbt :(

Here are the logs:
    
	[info] Loading global plugins from C:\Users\emmanuel.pot\.sbt\0.13\plugins
	[info] Updating {file:/C:/Users/emmanuel.pot/.sbt/0.13/plugins/}global-plugins...
	[info] Resolving de.heikoseeberger#sbt-fresh;3.1.10 ...
	[warn]  module not found: de.heikoseeberger#sbt-fresh;3.1.10
	[warn] ==== typesafe-ivy-releases: tried
	[warn]   https://repo.typesafe.com/typesafe/ivy-releases/de.heikoseeberger/sbt-fresh/scala_2.10/sbt_0.13/3.1.10/ivys/ivy.xml
	[warn] ==== sbt-plugin-releases: tried
	[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/de.heikoseeberger/sbt-fresh/scala_2.10/sbt_0.13/3.1.10/ivys/ivy.xml
	[warn] ==== local: tried
	[warn]   C:\Users\emmanuel.pot\.ivy2\local\de.heikoseeberger\sbt-fresh\scala_2.10\sbt_0.13\3.1.10\ivys\ivy.xml
	[warn] ==== public: tried
	[warn]   https://repo1.maven.org/maven2/de/heikoseeberger/sbt-fresh_2.10_0.13/3.1.10/sbt-fresh-3.1.10.pom
	[warn] ==== local-preloaded-ivy: tried
	[warn]   C:\Users\emmanuel.pot\.sbt\preloaded\de.heikoseeberger\sbt-fresh\3.1.10\ivys\ivy.xml
	[warn] ==== local-preloaded: tried
	[warn]   file:/C:/Users/emmanuel.pot/.sbt/preloaded/de/heikoseeberger/sbt-fresh_2.10_0.13/3.1.10/sbt-fresh-3.1.10.pom
	[warn] ==== Sonatype OSS Releases: tried
	[warn]   https://oss.sonatype.org/content/repositories/releases/de/heikoseeberger/sbt-fresh_2.10_0.13/3.1.10/sbt-fresh-3.1.10.pom
	[warn] ==== Sonatype OSS Snapshots: tried
	[warn]   https://oss.sonatype.org/content/repositories/snapshots/de/heikoseeberger/sbt-fresh_2.10_0.13/3.1.10/sbt-fresh-3.1.10.pom
	[info] Resolving org.fusesource.jansi#jansi;1.4 ...
	[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
	[warn]  ::          UNRESOLVED DEPENDENCIES         ::
	[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
	[warn]  :: de.heikoseeberger#sbt-fresh;3.1.10: not found

**Comment by hseeberger** [comment]
Just added this to the README: "Requirements: sbt 1.0 or higher"

**Comment by epot** [comment]
Oops, thanks!!

**Comment by epot** [comment]
Small comment: there is still one "0.13" reference in the readme, that may confuses dummies like me :).

**Comment by hseeberger** [comment]
Thanks!
