### ISSUE TITLE
Let users to customize license setting

### ISSUE THREAD

**Issue by rockjam** [sbt/sbt-fresh#13]
Thank you a lot for this plugin. It's much better than copy-paste approach.
What do you think about letting users to customize license, that will be used in source headers? I can make contribution at spare time.

**Comment by hseeberger** [comment]
@rockjam, there's already a plugin for adding customizable headers: https://github.com/sbt/sbt-header. This plugin by intention should remain minimal and opinionated.

**Comment by rockjam** [comment]
I understand your point. I knew about sbt-header plugin. Well, this means I need to customize couple lines manually in fresh build.

**Comment by hseeberger** [comment]
Yeah, create you own fork.
