### ISSUE TITLE
Add Metals' files to .gitignore

### ISSUE THREAD

**Issue by BranislavLazic** [sbt/sbt-fresh#162]
There's a new language server for Scala - [Metals](https://scalameta.org/metals/). By default, directories and files (.metals and .bloop) created by Metals are not listed in .gitignore generated by sbt-fresh. Can we update Template to ignore these files?

**Comment by hseeberger** [comment]
Sure. PR please ;-)

**Comment by BranislavLazic** [comment]
@hseeberger After implementing a change, can I test it somehow?

**Comment by hseeberger** [comment]
Closed by #163.
