### ISSUE TITLE
Unsupported compiler options in Scala 2.13

### ISSUE THREAD

**Issue by pbvie** [sbt/sbt-fresh#165]
The compiler options `-Ypartial-unification` and `-Ywarn-unused-import` are no longer supported in Scala 2.13.

Compilation of projects created with sbt-fresh 5.2.0 fail with
```
bad option: '-Ypartial-unification'
```
and after removing that option
```
bad option: '-Ywarn-unused-import'
```

The [release notes](https://github.com/scala/scala/releases/tag/v2.13.0) say that `The compiler no longer accepts -Ypartial-unification` (since it's not needed anymore) and I believe `-Ywarn-unused-import` should be replaced with `-Ywarn-unused:imports`.

If you agree with those changes, I'll create a PR.

**Comment by hseeberger** [comment]
Good catch! PR would be very much appreciated.

**Comment by pbvie** [comment]
Done :)

Suggestion: Why not add `> compile` to the scripted test to catch compilation errors automatically?

**Comment by hseeberger** [comment]
Hey, that sounds like a nifty trick! Will do.
