### ISSUE TITLE
Problems with `unmanagedSourceDirectories` on cross compile projects.

### ISSUE THREAD

**Issue by jan0sch** [sbt/sbt-fresh#184]
Hi,

I just ran into a problem when cross compiling a project and there was code in the "main" path like `scala` and specific versions in `scala-2.12` and `scala-2.13` paths.
However the compiler complained about not being able to find the included classes.
After some digging and help removing the following settings helped:

```
Compile / unmanagedSourceDirectories := Seq((Compile / scalaSource).value),
Test / unmanagedSourceDirectories := Seq((Test / scalaSource).value),
```

Should I provide a PR for removing them or simply mention that in the README?

Kind regards,

Jens

**Comment by hseeberger** [comment]
I think these settings are a leftover of some time when some IDE or other tool created all source directories. As most projects do not need the version specific paths I found these unnecessary directories annoying. 

But nowadays everybody seems to use IntelliJ or editors which do not automatically create the source directories – let's get rid of these settings. A PR would be welcome.

**Comment by jan0sch** [comment]
PR is here: https://github.com/sbt/sbt-fresh/pull/185
