### ISSUE TITLE
Consider updating .travis.yml to Open JDK 8

### ISSUE THREAD

**Issue by BranislavLazic** [sbt/sbt-fresh#192]
Using default value for JDK in `.travis.yml` file will result in the following error:

```
Expected feature release number in range of 9 to 15, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

As explained [here](https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365/2), this is a side effect of updating default Travis build env. from Trusty to Xenial.

Setting the value for jdk in `.travis.yml` to `openjdk8` fixes the issue.

**Comment by hseeberger** [comment]
Thanks. PR welcome ;-)
