### ISSUE TITLE
Non fresh projects not working with fresh plugin installed

### ISSUE THREAD

**Issue by dschmitz** [sbt/sbt-fresh#23]
If you issue sbt command in a non fresh generated project one gets the following error stacktrace

$ sbt
[info] Loading global plugins from /Users/schmitda/.sbt/0.13/plugins
[info] Loading project definition from /Users/schmitda/Documents/workspace/sfp/project
java.lang.NoClassDefFoundError: de/heikoseeberger/sbtfresh/FreshPlugin$autoImport$
	at $ba3f03fc201474796b2d$.$sbtdef(/Users/schmitda/.sbt/0.13/build.sbt:2)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by hseeberger** [comment]
I don't think this related to sbt-fresh. `/Users/schmitda/.sbt/0.13/build.sbt:2` indicates that you have some settings for sbt-fresh in your global settings file.

- Have you added sbt-fresh to your global plugins file (/Users/schmitda/.sbt/0.13/plugins/plugins.sbt)?
- Have you recently upgraded something, either sbt, sbt-fresh or some other plugins? In this case, please delete all target directories in `/Users/schmitda/Documents/workspace/sfp` and in `/Users/schmitda/.sbt/0.13` (`find . -name target | xargs rm -r`)

**Comment by dschmitz** [comment]
Hi Heiko,
I already had the global plugins.sbt entry for sbt fresh. I basically followed your README instructions. 
However removing target folders fixed the issue.  So how does this come about?

Regards
David

**Comment by hseeberger** [comment]
This happens sometimes when you upgrade (global) plugins and these bring in incompatible transitive dependencies. It's a known sbt issue.
