### ISSUE TITLE
License not found when creating new project

### ISSUE THREAD

**Issue by bblaine** [sbt/sbt-fresh#55]
I got an error when creating a new project with `fresh license=gpl3`. It looks like the proper license isn't getting imported. If I change to `import de.heikoseeberger.sbtheader.license.Apache2_0` to `import de.heikoseeberger.sbtheader.license.GPLv3` just before `headerSettings` it works. Same thing for other licenses; it always defaults to the Apache 2 license.

Here's the output:

```
sbt

...

> fresh license=gpl3

...

/tmp/SBTFreshTest/build.sbt:86: error: not found: value GPLv3

    headers := Map("scala" -> GPLv3("2016", "Brian Blaine"))
                              ^

sbt.compiler.EvalException: Type error in expression

[error] sbt.compiler.EvalException: Type error in expression

[error] Use 'last' for the full log.

Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

```

SBT info:

```sbt --version

sbt launcher version 0.13.6
```

```
cat ~/.sbt/0.13/plugins/plugins.sbt

addSbtPlugin("org.ensime" % "sbt-ensime" % "0.5.1")

addSbtPlugin("de.heikoseeberger" % "sbt-fresh" % "2.0.0")
```

**Comment by hseeberger** [comment]
Yeah, we should probably import all the licenses by the wildcard. PRs are welcome!

**Comment by bblaine** [comment]
Is it just a matter of changing the line `import de.heikoseeberger.sbtheader.license.Apache2_0` to `import de.heikoseeberger.sbtheader.license._` [on line 141](https://github.com/sbt/sbt-fresh/blob/master/src/main/scala/de/heikoseeberger/sbtfresh/Template.scala#L141)?
