### ISSUE TITLE
fatal scalariform error on first project load

### ISSUE THREAD

**Issue by caoilte** [sbt/sbt-fresh#7]
I get the following error after loading a project generated by fresh (0.2.3) for the first time

```
[error] /Users/caoilteoconnor/scala/test/project/Build.scala:33: value autoImport is not a member of object com.typesafe.sbt.SbtScalariform
[error]     SbtScalariform.autoImport.scalariformPreferences := SbtScalariform.autoImport.scalariformPreferences.value
[error]                    ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

I ran fresh with a brew installed 0.13.7 on a mac.

**Comment by hseeberger** [comment]
Please use sbt 0.13.9 and let me know if this help.

**Comment by caoilte** [comment]
yeah that works. I didn't realise there were such backward incompatible changes in the last few releases. apologies.
