### ISSUE TITLE
license=none not working

### ISSUE THREAD

**Issue by dschmitz** [sbt/sbt-fresh#79]
Overwriting my default license via command line e.g. apache20 to none does not work. What works is setting license to None in global build.sbt

**Comment by hseeberger** [comment]
This is not (yet) expected to work, see the documentation in the README. You should be able to define
`set freshLicense := None` in the sbt session before issuing the `fresh` command. Does that work?

**Comment by ksilin** [comment]
confirmed, working.

**Comment by hseeberger** [comment]
As sbt-header needs some tweaks if it can't autodetect the license, i.e. if you want to use none, it's not reasonable to allow this argument here.
