### ISSUE TITLE
Generated projects that don't use Travis are broken

### ISSUE THREAD

**Issue by pbvie** [sbt/sbt-fresh#82]
Creating a new project with `setUpTravis := false` breaks the build. I.e. compiling the project gives the following error:

```
[error] 'jvm-1.8' is not a valid choice for '-target'
[error] bad option: '-target:jvm-1.8'
[error] (compile:compileIncremental) Compilation failed
```

This can be (manually) fixed by uncommenting `scalaVersion := "2.12.1",` in the generated `build.sbt`.

To prevent the creation of broken projects it would probably be necessary that `Template.automateScalafmtPlugin` is aware of the configuration (i.e. getting it via parameter) so the Scala version is only commented out if setting up Travis is disabled. Does that sound good? If so, I could create a PR on the weekend.

Thanks
Petra

**Comment by hseeberger** [comment]
Good catch! The suggested fix sounds good, yet it should be Template.buildSbt, right?

**Comment by pbvie** [comment]
Thanks! Oh, right...definitely `Template.buildSbt` :slightly_smiling_face:
